# This file was generated by GoReleaser. DO NOT EDIT.
class Hostctl < Formula
  desc "manage your hosts file like a pro"
  homepage "https://github.com/guumaster/hostctl"
  version "0.5.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/guumaster/hostctl/releases/download/v0.5.4/hostctl_0.5.4_macOS_64-bit.tar.gz"
    sha256 "ddf25b500d131ebea1643718fc5af3a25b9b044953f0d592bb732db5f1a357bc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/guumaster/hostctl/releases/download/v0.5.4/hostctl_0.5.4_linux_64-bit.tar.gz"
      sha256 "d989d23dc9815dd87a3e348b1a2d9bc6e6c40823a04f78d39eef4f411f0b0fb0"
    end
  end

  def install
    bin.install "hostctl"
  end

  def caveats; <<~EOS
    Remember to add sudo to modify your hosts file.
  EOS
  end
end
