# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostctl < Formula
  desc "Your dev tool to manage /etc/hosts like a pro"
  homepage "https://github.com/guumaster/hostctl"
  version "1.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guumaster/hostctl/releases/download/v1.1.4/hostctl_1.1.4_macOS_64-bit.tar.gz"
      sha256 "f55d36af4223dbf55f7402b3074a4861e5dc63097ccb8f6a91b7f2acc1036cfe"

      def install
        bin.install "hostctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guumaster/hostctl/releases/download/v1.1.4/hostctl_1.1.4_macOS_arm64.tar.gz"
      sha256 "151f19dd77403cce20760ca97bf27d9b5a20b93e0b32f5caf62c5089e1648d4b"

      def install
        bin.install "hostctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guumaster/hostctl/releases/download/v1.1.4/hostctl_1.1.4_linux_arm64.tar.gz"
      sha256 "9b3053ac8a0c7de535c07979d1e76b2c5cbeeb44434d2335d3e0c3e776121a9c"

      def install
        bin.install "hostctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/guumaster/hostctl/releases/download/v1.1.4/hostctl_1.1.4_linux_64-bit.tar.gz"
      sha256 "f4ec3c9f9d54633511251834ce98d409464fb1c0d970f9c865a880e1160db30f"

      def install
        bin.install "hostctl"
      end
    end
  end

  def caveats
    <<~EOS
      Remember to add sudo to modify your hosts file.
    EOS
  end
end
